package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MoodEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoodEntryAllPropertiesEquals(MoodEntry expected, MoodEntry actual) {
        assertMoodEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertMoodEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoodEntryAllUpdatablePropertiesEquals(MoodEntry expected, MoodEntry actual) {
        assertMoodEntryUpdatableFieldsEquals(expected, actual);
        assertMoodEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoodEntryAutoGeneratedPropertiesEquals(MoodEntry expected, MoodEntry actual) {
        assertThat(actual)
            .as("Verify MoodEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoodEntryUpdatableFieldsEquals(MoodEntry expected, MoodEntry actual) {
        assertThat(actual)
            .as("Verify MoodEntry relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getMood()).as("check mood").isEqualTo(expected.getMood()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMoodEntryUpdatableRelationshipsEquals(MoodEntry expected, MoodEntry actual) {
        // empty method
    }
}
